version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.8"
  commands:
    - python -m ipykernel install --user --name python3



python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py
